// Global variables to store parsed DICOM data
let currentDicomDataSet = null;
let pixelDataElement = null;

// Windowing variables
let currentWindowLevel = 50;  // Default WL
let currentWindowWidth = 400; // Default WW
let rawPixelMin = 0;          // Min value in the raw pixel data (for slider range)
let rawPixelMax = 255;        // Max value in the raw pixel data

// Zoom and Pan variables
let currentZoom = 1.0;
let panX = 0;
let panY = 0;
let baseImageData = null; // Will store the ImageData generated by windowing
let isPanning = false;
let lastPanX = 0; // Mouse X position at start of pan
let lastPanY = 0; // Mouse Y position at start of pan
const MIN_ZOOM = 0.1;
const MAX_ZOOM = 10.0;

// Rotation and Flip variables
let currentRotation = 0; // Angle in degrees (0, 90, 180, 270)
let flipHorizontal = false;
let flipVertical = false;

// Ensure dicomParser is available
if (typeof dicomParser === 'undefined') {
    alert('dicomParser library is not loaded. Please check the script link in index.html.');
}

document.addEventListener('DOMContentLoaded', () => {
    console.log('DOM fully loaded and parsed');

    const fileInput = document.getElementById('dicomFile');
    const canvas = document.getElementById('dicomCanvas');
    const ctx = canvas.getContext('2d');

    // Metadata display elements
    const patientNameSpan = document.getElementById('patientName');
    const patientIdSpan = document.getElementById('patientId');
    const studyDateSpan = document.getElementById('studyDate');
    const modalitySpan = document.getElementById('modality');
    const seriesNumberSpan = document.getElementById('seriesNumber'); // New
    const instanceNumberSpan = document.getElementById('instanceNumber'); // New

    // Windowing UI elements
    const wlSlider = document.getElementById('windowLevelSlider');
    const wwSlider = document.getElementById('windowWidthSlider');
    const wlValueSpan = document.getElementById('wlValue');
    const wwValueSpan = document.getElementById('wwValue');
    const resetViewButton = document.getElementById('resetViewButton'); 
    const rotateCWButton = document.getElementById('rotateCWButton'); 
    const rotateCCWButton = document.getElementById('rotateCCWButton'); 
    const flipHorizontalButton = document.getElementById('flipHorizontalButton'); 
    const flipVerticalButton = document.getElementById('flipVerticalButton'); 


    if (fileInput) {
        fileInput.addEventListener('change', handleFileSelect);
    } else {
        console.error('File input not found!');
    }

    // Setup event listeners for windowing sliders
    wlSlider.addEventListener('input', (e) => {
        currentWindowLevel = parseFloat(e.target.value);
        wlValueSpan.textContent = currentWindowLevel.toFixed(0);
        if (currentDicomDataSet) renderDicomImage(); 
    });

    wwSlider.addEventListener('input', (e) => {
        currentWindowWidth = parseFloat(e.target.value);
        wwValueSpan.textContent = currentWindowWidth.toFixed(0);
        if (currentDicomDataSet) renderDicomImage(); 
    });

    function resetMetadataDisplay() {
        patientNameSpan.textContent = 'N/A';
        patientIdSpan.textContent = 'N/A';
        studyDateSpan.textContent = 'N/A';
        modalitySpan.textContent = 'N/A';
        seriesNumberSpan.textContent = 'N/A'; // New
        instanceNumberSpan.textContent = 'N/A'; // New
    }

    function handleFileSelect(event) {
        const file = event.target.files[0];
        if (!file) {
            console.log('No file selected.');
            return;
        }
        console.log('File selected:', file.name);
        resetMetadataDisplay(); // Reset display for new file

        const reader = new FileReader();
        reader.onload = function(fileEvent) {
            const arrayBuffer = fileEvent.target.result;
            try {
                const byteArray = new Uint8Array(arrayBuffer);
                currentDicomDataSet = dicomParser.parseDicom(byteArray);

                const patientName = currentDicomDataSet.string('x00100010') || 'N/A';
                const patientId = currentDicomDataSet.string('x00100020') || 'N/A';
                const studyDate = currentDicomDataSet.string('x00080020') || 'N/A';
                const modality = currentDicomDataSet.string('x00080060') || 'N/A';
                const seriesNumber = currentDicomDataSet.string('x00200011') || 'N/A'; // New
                const instanceNumber = currentDicomDataSet.string('x00200013') || 'N/A'; // New


                console.log('Patient Name:', patientName);
                console.log('Patient ID:', patientId);
                console.log('Study Date:', studyDate);
                console.log('Modality:', modality);
                console.log('Series Number:', seriesNumber); // New
                console.log('Instance Number:', instanceNumber); // New

                // Update HTML metadata spans
                patientNameSpan.textContent = patientName;
                patientIdSpan.textContent = patientId;
                studyDateSpan.textContent = studyDate;
                modalitySpan.textContent = modality;
                seriesNumberSpan.textContent = seriesNumber; // New
                instanceNumberSpan.textContent = instanceNumber; // New

                const rows = currentDicomDataSet.uint16('x00280010');
                const columns = currentDicomDataSet.uint16('x00280011');
                const bitsAllocated = currentDicomDataSet.uint16('x00280100');
                const photometricInterpretation = currentDicomDataSet.string('x00280004');
                
                pixelDataElement = currentDicomDataSet.elements.x7fe00010;

                if (pixelDataElement) {
                    console.log('Pixel Data found. Length:', pixelDataElement.length);
                    console.log('Image Dimensions:', columns, 'x', rows);
                    console.log('Bits Allocated:', bitsAllocated);
                    console.log('Photometric Interpretation:', photometricInterpretation);
                    
                    // Reset zoom and pan for the new image (will be done in renderDicomImage)

                    // Calculate rawPixelMin and rawPixelMax for slider setup
                    // This logic is similar to what was in renderDicomImage for 16-bit normalization
                    const dicomPixelDataOffset = pixelDataElement.dataOffset;
                    const dicomPixelDataLength = pixelDataElement.length;
                    const rawDicomPixelBuffer = currentDicomDataSet.byteArray.slice(dicomPixelDataOffset, dicomPixelDataOffset + dicomPixelDataLength);
                    let tempTypedPixelArray;
                    if (bitsAllocated === 8) {
                        rawPixelMin = 0;
                        rawPixelMax = 255;
                    } else if (bitsAllocated === 16) {
                        const pixelRepresentation = currentDicomDataSet.uint16('x00280103'); // 0 = unsigned, 1 = signed
                        if (pixelRepresentation === 0) { 
                            tempTypedPixelArray = new Uint16Array(rawDicomPixelBuffer.buffer, rawDicomPixelBuffer.byteOffset, rawDicomPixelBuffer.length / 2);
                        } else { 
                            tempTypedPixelArray = new Int16Array(rawDicomPixelBuffer.buffer, rawDicomPixelBuffer.byteOffset, rawDicomPixelBuffer.length / 2);
                        }
                        rawPixelMin = Infinity;
                        rawPixelMax = -Infinity;
                        for (let i = 0; i < tempTypedPixelArray.length; i++) {
                            if (tempTypedPixelArray[i] < rawPixelMin) rawPixelMin = tempTypedPixelArray[i];
                            if (tempTypedPixelArray[i] > rawPixelMax) rawPixelMax = tempTypedPixelArray[i];
                        }
                    } else { // Fallback for unsupported bit depths, though render will also catch this
                        rawPixelMin = 0;
                        rawPixelMax = 255;
                    }
                     if (rawPixelMax === rawPixelMin) rawPixelMax = rawPixelMin + 1; // Avoid range of 0


                    // Attempt to get WL/WW from DICOM tags
                    let wcTag = currentDicomDataSet.elements.x00281050; // WindowCenter
                    let wwTag = currentDicomDataSet.elements.x00281051; // WindowWidth

                    if (wcTag && wwTag) {
                        currentWindowLevel = currentDicomDataSet.floatString('x00281050', 0);
                        currentWindowWidth = currentDicomDataSet.floatString('x00281051', 0);
                        console.log(`Found DICOM WC: ${currentWindowLevel}, WW: ${currentWindowWidth}`);
                    } else {
                        currentWindowLevel = (rawPixelMax + rawPixelMin) / 2;
                        currentWindowWidth = (rawPixelMax - rawPixelMin);
                        console.log(`Calculated default WC: ${currentWindowLevel}, WW: ${currentWindowWidth}`);
                    }
                    if (currentWindowWidth < 1) currentWindowWidth = 1;

                    // Update slider ranges and values
                    wlSlider.min = rawPixelMin.toString();
                    wlSlider.max = rawPixelMax.toString();
                    wlSlider.value = currentWindowLevel.toString();
                    wlValueSpan.textContent = currentWindowLevel.toFixed(0);

                    wwSlider.min = "1";
                    wwSlider.max = (rawPixelMax - rawPixelMin).toString();
                    wwSlider.value = currentWindowWidth.toString();
                    wwValueSpan.textContent = currentWindowWidth.toFixed(0);
                    
                    renderDicomImage(); // This will now prepare baseImageData and call drawCanvas
                } else {
                    console.error('Pixel Data (x7fe00010) not found in this DICOM file.');
                    alert('Pixel Data not found. Cannot display image.');
                    baseImageData = null; // Clear base image data
                    drawCanvas(); // Clear canvas display
                }
                
            } catch (error) {
                console.error('Error parsing DICOM file:', error);
                alert('Failed to parse DICOM file. See console for details. Error: ' + error.message);
                currentDicomDataSet = null;
                pixelDataElement = null;
                resetMetadataDisplay(); 
                baseImageData = null;
                drawCanvas(); 
            }
        };
        reader.onerror = function(error) {
            console.error('FileReader error:', error);
            alert('Error reading file. See console for details.');
            currentDicomDataSet = null;
            pixelDataElement = null;
            resetMetadataDisplay();
            baseImageData = null;
            drawCanvas();
        };
        reader.readAsArrayBuffer(file);
    }

    function renderDicomImage() { // Now primarily prepares baseImageData
        if (!currentDicomDataSet || !pixelDataElement) {
            console.error("No DICOM data or pixel data element available to render.");
            baseImageData = null;
            drawCanvas(); // Clear canvas
            return;
        }

        const rows = currentDicomDataSet.uint16('x00280010');
        const columns = currentDicomDataSet.uint16('x00280011');
        const bitsAllocated = currentDicomDataSet.uint16('x00280100');
        const photometricInterpretation = currentDicomDataSet.string('x00280004').trim();

        // Canvas dimensions are set to the image dimensions.
        // CSS max-width/max-height will constrain the viewable area.
        canvas.width = columns;
        canvas.height = rows;

        const generatedImageData = ctx.createImageData(columns, rows); // Use a local var
        const pixelData = generatedImageData.data; 

        const dicomPixelDataOffset = pixelDataElement.dataOffset;
        const dicomPixelDataLength = pixelDataElement.length;
        const rawDicomPixelBuffer = currentDicomDataSet.byteArray.slice(dicomPixelDataOffset, dicomPixelDataOffset + dicomPixelDataLength);
        
        let typedPixelArray;
        // Create the appropriate typed array based on BitsAllocated and PixelRepresentation
        if (bitsAllocated === 8) {
            typedPixelArray = new Uint8Array(rawDicomPixelBuffer.buffer, rawDicomPixelBuffer.byteOffset, rawDicomPixelBuffer.length);
        } else if (bitsAllocated === 16) {
            const pixelRepresentation = currentDicomDataSet.uint16('x00280103'); // 0 = unsigned, 1 = signed
            if (pixelRepresentation === 0) { 
                typedPixelArray = new Uint16Array(rawDicomPixelBuffer.buffer, rawDicomPixelBuffer.byteOffset, rawDicomPixelBuffer.length / 2);
            } else { 
                typedPixelArray = new Int16Array(rawDicomPixelBuffer.buffer, rawDicomPixelBuffer.byteOffset, rawDicomPixelBuffer.length / 2);
            }
        } else {
            alert(`Unsupported bits allocated: ${bitsAllocated}. Only 8-bit and 16-bit grayscale are currently supported.`);
            console.error(`Unsupported bits allocated: ${bitsAllocated}`);
            ctx.clearRect(0, 0, canvas.width, canvas.height);
            return;
        }

        const level = currentWindowLevel;
        const width = currentWindowWidth;
        const ymin = 0;
        const ymax = 255;
        const low = level - width / 2;
        const high = level + width / 2;

        for (let i = 0; i < typedPixelArray.length; i++) {
            let rawValue = typedPixelArray[i];
            let pixelValue;

            if (rawValue <= low) {
                pixelValue = ymin;
            } else if (rawValue > high) {
                pixelValue = ymax;
            } else {
                pixelValue = ((rawValue - low) / width) * (ymax - ymin) + ymin;
            }
            
            if (photometricInterpretation === "MONOCHROME1") {
                pixelValue = ymax - pixelValue; // or 255 - pixelValue
            }

            pixelValue = Math.max(0, Math.min(255, Math.round(pixelValue)));

            pixelData[i * 4 + 0] = pixelValue;
            pixelData[i * 4 + 1] = pixelValue; 
            pixelData[i * 4 + 2] = pixelValue; 
            pixelData[i * 4 + 3] = 255;      
        }

        baseImageData = generatedImageData; // Store the result of windowing etc.
        
        // Reset zoom, pan, rotation, and flip for the new image (Step 5)
        currentZoom = 1.0;
        panX = 0;
        panY = 0;
        currentRotation = 0;
        flipHorizontal = false;
        flipVertical = false;
        
        drawCanvas(); // New function to actually draw on canvas with zoom/pan
        console.log('Base image data prepared. Initial draw called.');
    }

    function drawCanvas() { // Modified for Step 4
        if (!ctx || !canvas) return; 

        ctx.clearRect(0, 0, canvas.width, canvas.height);

        if (!baseImageData) {
            return;
        }

        const imgWidth = baseImageData.width;
        const imgHeight = baseImageData.height;

        // Create a temporary canvas to hold the base image and apply rotation/flip
        const tempCanvas = document.createElement('canvas');
        const tempCtx = tempCanvas.getContext('2d');
        
        // Adjust tempCanvas size for 90/270 degree rotations
        if (currentRotation === 90 || currentRotation === 270) {
            tempCanvas.width = imgHeight;
            tempCanvas.height = imgWidth;
        } else {
            tempCanvas.width = imgWidth;
            tempCanvas.height = imgHeight;
        }

        // Translate context to center of tempCanvas for rotation/flip
        tempCtx.translate(tempCanvas.width / 2, tempCanvas.height / 2);

        // Apply flip
        if (flipHorizontal) tempCtx.scale(-1, 1);
        if (flipVertical) tempCtx.scale(1, -1);

        // Apply rotation
        tempCtx.rotate(currentRotation * Math.PI / 180);
        
        // Draw baseImageData onto tempCtx
        // Since we translated, we need to draw relative to the new center (0,0)
        // taking into account original image dimensions.
        tempCtx.putImageData(baseImageData, -imgWidth / 2, -imgHeight / 2);
        
        // --- Main canvas drawing ---
        ctx.save();
        ctx.translate(panX, panY);
        ctx.scale(currentZoom, currentZoom);

        // Draw the (potentially rotated/flipped) image from the temporary canvas
        ctx.drawImage(tempCanvas, 0, 0); 

        ctx.restore();
        
        // Example: console.log(`Zoom: ${currentZoom.toFixed(2)}, Pan: (${panX.toFixed(0)}, ${panY.toFixed(0)})`);
    }


    // Initial Canvas State (optional, as CSS handles background)
    // Set initial cursor style
    canvas.style.cursor = 'grab';

    // Reset View Button Listener (Modified for Step 6)
    resetViewButton.addEventListener('click', () => {
        if (!baseImageData) return;
        currentZoom = 1.0;
        panX = 0;
        panY = 0;
        currentRotation = 0;      
        flipHorizontal = false;   
        flipVertical = false;     
        drawCanvas();
    });

    // Rotation and Flip Button Listeners (Step 3)
    rotateCWButton.addEventListener('click', () => {
        if (!baseImageData) return;
        currentRotation = (currentRotation + 90) % 360;
        drawCanvas();
    });

    rotateCCWButton.addEventListener('click', () => {
        if (!baseImageData) return;
        currentRotation = (currentRotation - 90 + 360) % 360;
        drawCanvas();
    });

    flipHorizontalButton.addEventListener('click', () => {
        if (!baseImageData) return;
        flipHorizontal = !flipHorizontal;
        drawCanvas();
    });

    flipVerticalButton.addEventListener('click', () => {
        if (!baseImageData) return;
        flipVertical = !flipVertical;
        drawCanvas();
    });

    // Zoom Implementation
    canvas.addEventListener('wheel', (event) => {
        if (!baseImageData) return;
        event.preventDefault(); 

        const zoomFactor = 1.1;
        const rect = canvas.getBoundingClientRect();
        const mouseX = event.clientX - rect.left; 
        const mouseY = event.clientY - rect.top; 

        const imageX = (mouseX - panX) / currentZoom;
        const imageY = (mouseY - panY) / currentZoom;

        let newZoom = currentZoom;
        if (event.deltaY < 0) { 
            newZoom = currentZoom * zoomFactor;
        } else { 
            newZoom = currentZoom / zoomFactor;
        }
        currentZoom = Math.max(MIN_ZOOM, Math.min(MAX_ZOOM, newZoom));
        
        panX = mouseX - imageX * currentZoom;
        panY = mouseY - imageY * currentZoom;

        drawCanvas();
    });

    // Pan Implementation
    canvas.addEventListener('mousedown', (event) => {
        if (!baseImageData) return;
        isPanning = true;
        lastPanX = event.clientX;
        lastPanY = event.clientY;
        canvas.style.cursor = 'grabbing';
    });

    canvas.addEventListener('mousemove', (event) => {
        if (!isPanning || !baseImageData) return;
        
        const dx = event.clientX - lastPanX;
        const dy = event.clientY - lastPanY;
        
        panX += dx;
        panY += dy;
        
        lastPanX = event.clientX;
        lastPanY = event.clientY;
        
        drawCanvas();
    });

    canvas.addEventListener('mouseup', () => {
        if (!baseImageData) return; // Check baseImageData here as well
        isPanning = false;
        canvas.style.cursor = 'grab'; 
    });

    canvas.addEventListener('mouseleave', () => { 
        if (!baseImageData) return; // Check baseImageData here as well
        isPanning = false;
        canvas.style.cursor = 'grab'; 
    });


    // Placeholder for UI updates
    // Example:
    // const wlSlider = document.getElementById('windowLevelSlider');
    // const wwSlider = document.getElementById('windowWidthSlider');
    // const wlValueSpan = document.getElementById('wlValue');
    // const wwValueSpan = document.getElementById('wwValue');

    // wlSlider.addEventListener('input', (e) => wlValueSpan.textContent = e.target.value);
    // wwSlider.addEventListener('input', (e) => wwValueSpan.textContent = e.target.value);

    console.log('JS DICOM Viewer initialized.');
});
